// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

typedef arma::imat integerMatrixType;
typedef arma::ivec integerVectorType;
typedef arma::mat numericMatrixType;
typedef arma::vec numericVectorType;
typedef arma::uvec sizeVectorType;

// computeCombinations
size_t computeCombinations(const size_t n);
RcppExport SEXP npideal_computeCombinations(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const size_t >::type n(nSEXP);
    __result = Rcpp::wrap(computeCombinations(n));
    return __result;
END_RCPP
}
// votetest
List votetest(const integerMatrixType& v1, const integerMatrixType& v2, IntegerVector focus, size_t numLegisShuffles, const size_t numBootstrapSims);
RcppExport SEXP npideal_votetest(SEXP v1SEXP, SEXP v2SEXP, SEXP focusSEXP, SEXP numLegisShufflesSEXP, SEXP numBootstrapSimsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const integerMatrixType& >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< const integerMatrixType& >::type v2(v2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type focus(focusSEXP);
    Rcpp::traits::input_parameter< size_t >::type numLegisShuffles(numLegisShufflesSEXP);
    Rcpp::traits::input_parameter< const size_t >::type numBootstrapSims(numBootstrapSimsSEXP);
    __result = Rcpp::wrap(votetest(v1, v2, focus, numLegisShuffles, numBootstrapSims));
    return __result;
END_RCPP
}
// rankAgreeR
numericVectorType rankAgreeR(const integerMatrixType& v, const size_t i, const size_t j);
RcppExport SEXP npideal_rankAgreeR(SEXP vSEXP, SEXP iSEXP, SEXP jSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const integerMatrixType& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const size_t >::type i(iSEXP);
    Rcpp::traits::input_parameter< const size_t >::type j(jSEXP);
    __result = Rcpp::wrap(rankAgreeR(v, i, j));
    return __result;
END_RCPP
}
// voteest
NumericVector voteest(const integerMatrixType& v, size_t right, size_t left, const size_t maxLegisSamples);
RcppExport SEXP npideal_voteest(SEXP vSEXP, SEXP rightSEXP, SEXP leftSEXP, SEXP maxLegisSamplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const integerMatrixType& >::type v(vSEXP);
    Rcpp::traits::input_parameter< size_t >::type right(rightSEXP);
    Rcpp::traits::input_parameter< size_t >::type left(leftSEXP);
    Rcpp::traits::input_parameter< const size_t >::type maxLegisSamples(maxLegisSamplesSEXP);
    __result = Rcpp::wrap(voteest(v, right, left, maxLegisSamples));
    return __result;
END_RCPP
}
